import { ZodMessages } from '~/common/constants'

export const WasteMessages = [
  // SUCCESS MESSAGES
  'WASTE_INVENTORY_CREATED_SUCCESS',
  'WASTE_INVENTORY_UPDATED_SUCCESS',
  'WASTE_INVENTORY_DELETED_SUCCESS',
  'WASTE_INVENTORY_RESTORED_SUCCESS',
  'WASTE_INVENTORY_FETCH_SUCCESS',
  'WASTE_CATEGORY_FETCH_SUCCESS',
  'WASTE_ANALYSIS_COMPLETED_SUCCESS',

  // ERROR MESSAGES
  'WASTE_INVENTORY_CREATION_FAILED',
  'WASTE_INVENTORY_UPDATE_FAILED',
  'WASTE_INVENTORY_DELETE_FAILED',
  'WASTE_INVENTORY_RESTORE_FAILED',
  'WASTE_INVENTORY_FETCH_FAILED',
  'WASTE_CATEGORY_FETCH_FAILED',
  'WASTE_CATEGORY_INVALID',
  'WASTE_INVENTORY_NOT_FOUND',
  'WASTE_DUPLICATE_NAME',
  'WASTE_INVALID_COMPOSITION',
  'WASTE_ANALYSIS_FAILED',

  ...ZodMessages,
] as const
