import { ZodMessages } from '~/common/constants'

export const ProcessingModulesMessages = [
  // SUCCESS
  'MODULE_CREATED_SUCCESS',
  'MODULE_FETCH_SUCCESS',
  'MODULE_LIST_FETCH_SUCCESS',
  'MODULE_UPDATED_SUCCESS',
  'MODULE_RESERVED_SUCCESS',
  'MODULE_RELEASED_SUCCESS',
  'MODULE_MAINTENANCE_SET_SUCCESS',

  // ERRORS
  'MODULE_CREATE_FAILED',
  'MODULE_FETCH_FAILED',
  'MODULE_LIST_FETCH_FAILED',
  'MODULE_UPDATE_FAILED',
  'MODULE_NOT_FOUND',
  'MODULE_RESERVE_FAILED',
  'MODULE_RELEASE_FAILED',
  'MODULE_MAINTENANCE_SET_FAILED',
  'MODULE_INVALID_STATUS',

  ...ZodMessages,
] as const
