import { ZodMessages } from '~/common/constants'

export const WasteMessages = [
  // SUCCESS MESSAGES
  'WASTE_MATERIAL_CREATED_SUCCESS',
  'WASTE_MATERIAL_UPDATED_SUCCESS',
  'WASTE_MATERIAL_DELETED_SUCCESS',
  'WASTE_MATERIAL_RESTORED_SUCCESS',
  'WASTE_MATERIAL_FETCH_SUCCESS',
  'WASTE_CATEGORY_FETCH_SUCCESS',
  'WASTE_ANALYSIS_COMPLETED_SUCCESS',

  // ERROR MESSAGES
  'WASTE_MATERIAL_CREATION_FAILED',
  'WASTE_MATERIAL_UPDATE_FAILED',
  'WASTE_MATERIAL_DELETE_FAILED',
  'WASTE_MATERIAL_RESTORE_FAILED',
  'WASTE_MATERIAL_FETCH_FAILED',
  'WASTE_CATEGORY_FETCH_FAILED',
  'WASTE_CATEGORY_INVALID',
  'WASTE_MATERIAL_NOT_FOUND',
  'WASTE_DUPLICATE_NAME',
  'WASTE_INVALID_COMPOSITION',
  'WASTE_ANALYSIS_FAILED',

  ...ZodMessages,
] as const
