import { ZodMessages } from '~/common/constants'

export const RecipesMessages = [
  // SUCCESS MESSAGES
  'RECIPE_CREATED_SUCCESS',
  'RECIPE_UPDATED_SUCCESS',
  'RECIPE_DELETED_SUCCESS',
  'RECIPE_FETCH_SUCCESS',
  'RECIPE_VALIDATED_SUCCESS',
  'RECIPE_RECOMMENDATIONS_SUCCESS',
  'RECIPE_DEACTIVATED_SUCCESS',

  // ERROR MESSAGES
  'RECIPE_CREATION_FAILED',
  'RECIPE_UPDATE_FAILED',
  'RECIPE_DELETE_FAILED',
  'RECIPE_FETCH_FAILED',
  'RECIPE_NOT_FOUND',
  'RECIPE_VALIDATION_FAILED',
  'RECIPE_RECOMMENDATIONS_FAILED',
  'RECIPE_INVALID_INPUTS',
  'RECIPE_INVALID_OUTPUTS',
  'RECIPE_INSUFFICIENT_MODULES',
  'RECIPE_IN_USE',

  ...ZodMessages,
] as const
